name: notif
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+4 # For SQLite database
  path: ^1.8.0 # For file and directory paths
  shared_preferences: ^2.0.15
  provider: ^6.0.0 # For state management
  curved_navigation_bar: ^1.0.0 # For curved navigation bar (if using this package)
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
